/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import FacebookImage from 'src/assets/images/Desktop5_Facebook.png';
import InstagramImage from 'src/assets/images/Desktop5_Instagram.png';
import TwitterImage from 'src/assets/images/Desktop5_Twitter.png';
import YoutubeImage from 'src/assets/images/Desktop5_Youtube.png';
import PngtreeSilhouetteOfRImage from 'src/assets/images/Desktop5___Pngtree_silhouette_of_religious_ceremony_in_9011399_1.png';
import { styled } from '@mui/material/styles';

const Desktop51 = styled('div')({
  backgroundColor: `rgba(237, 242, 244, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `2968px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle9 = styled('div')({
  background: `linear-gradient(-141.69deg, rgba(237, 50, 73, 0.92) -1.2321813110719626%, rgba(239, 35, 60, 1) -1.2321813110719626%, rgba(217, 217, 217, 0) 100.00000301005143%)`,
  borderRadius: `0px`,
  width: `1440px`,
  height: `2469px`,
  position: `absolute`,
  left: `0px`,
  top: `-14px`,
});

const Rectangle8 = styled('div')({
  backgroundColor: `rgba(43, 45, 66, 1)`,
  borderRadius: `0px`,
  width: `1440px`,
  height: `565px`,
  position: `absolute`,
  left: `0px`,
  top: `2403px`,
});

const PresensiKaryawanHari = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `800`,
  fontSize: `60px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `672px`,
  position: `absolute`,
  left: `164px`,
  top: `333px`,
});

const HaloYukAbsenDuluAgar = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `549px`,
  position: `absolute`,
  left: `166px`,
  top: `522px`,
});

const HaloSelamatDatang = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `438px`,
  position: `absolute`,
  left: `166px`,
  top: `252px`,
});

const Home = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `79px`,
  position: `absolute`,
  left: `796px`,
  top: `70px`,
});

const Absen = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `96px`,
  position: `absolute`,
  left: `948px`,
  top: `70px`,
});

const Instansi = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `600`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `109px`,
  position: `absolute`,
  left: `1117px`,
  top: `70px`,
});

const Rectangle2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(43, 45, 66, 1)`,
  boxSizing: `border-box`,
  borderRadius: `15px`,
  width: `630px`,
  height: `71px`,
  position: `absolute`,
  left: `166px`,
  top: `1549px`,
});

const Rectangle3 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(43, 45, 66, 1)`,
  boxSizing: `border-box`,
  borderRadius: `15px`,
  width: `630px`,
  height: `71px`,
  position: `absolute`,
  left: `166px`,
  top: `1668px`,
});

const Rectangle4 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(43, 45, 66, 1)`,
  boxSizing: `border-box`,
  borderRadius: `15px`,
  width: `630px`,
  height: `71px`,
  position: `absolute`,
  left: `166px`,
  top: `1787px`,
});

const Rectangle5 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(43, 45, 66, 1)`,
  boxSizing: `border-box`,
  borderRadius: `15px`,
  width: `630px`,
  height: `71px`,
  position: `absolute`,
  left: `166px`,
  top: `1906px`,
});

const Rectangle7 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(43, 45, 66, 1)`,
  boxSizing: `border-box`,
  borderRadius: `15px`,
  width: `630px`,
  height: `71px`,
  position: `absolute`,
  left: `166px`,
  top: `2026px`,
});

const Rectangle6 = styled('div')({
  backgroundColor: `rgba(43, 45, 66, 1)`,
  borderRadius: `15px`,
  width: `192px`,
  height: `71px`,
  position: `absolute`,
  left: `988px`,
  top: `2026px`,
});

const SilahkanIsiDataDiriK = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `700`,
  fontSize: `50px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `166px`,
  top: `1347px`,
});

const Nama = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `220px`,
  top: `1516px`,
});

const Nip = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `220px`,
  top: `1635px`,
});

const Bidang = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `220px`,
  top: `1754px`,
});

const Jabatan = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `220px`,
  top: `1873px`,
});

const Tanggal = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `220px`,
  top: `1992px`,
});

const Absen1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `600`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `1041px`,
  top: `2044px`,
});

const SayaTelahMemasukkanD = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(43, 45, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `288px`,
  position: `absolute`,
  left: `988px`,
  top: `2128px`,
});

const DinasKomunikasiInfor = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `600`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `824px`,
  height: `44px`,
  position: `absolute`,
  left: `164px`,
  top: `2484px`,
});

const Q0361431229 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `192px`,
  height: `36px`,
  position: `absolute`,
  left: `260px`,
  top: `2616px`,
});

const KominfoDenpasarkotaG = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `384px`,
  height: `36px`,
  position: `absolute`,
  left: `260px`,
  top: `2675px`,
});

const KominfostatistikDenp = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `480px`,
  height: `36px`,
  position: `absolute`,
  left: `260px`,
  top: `2740px`,
});

const FollowUs = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `164px`,
  top: `2811px`,
});

const JlMajapahitNo1DauhPu = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(217, 217, 217, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `261px`,
  top: `2552px`,
});

const Facebook = styled('img')({
  height: `34px`,
  width: `34px`,
  position: `absolute`,
  left: `425px`,
  top: `2810px`,
});

const Instagram = styled('img')({
  height: `34px`,
  width: `34px`,
  position: `absolute`,
  left: `320px`,
  top: `2810px`,
});

const Twitter = styled('img')({
  height: `34px`,
  width: `34px`,
  position: `absolute`,
  left: `373px`,
  top: `2810px`,
});

const Youtube = styled('img')({
  height: `34px`,
  width: `34px`,
  position: `absolute`,
  left: `478px`,
  top: `2810px`,
});

const S24822401 = styled('div')({
  borderRadius: `0px`,
  width: `641px`,
  height: `360px`,
  position: `absolute`,
  left: `676px`,
  top: `539px`,
});

const PngtreeSilhouetteOfR = styled('img')({
  height: `878px`,
  width: `1440px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `333px`,
});

function Desktop5(props) {
  return (
    <Desktop51 className={props.className}>
      <Rectangle9></Rectangle9>
      <Rectangle8></Rectangle8>
      <PresensiKaryawanHari>
        {`Presensi Karyawan Harian. Ayo Absen!`}
      </PresensiKaryawanHari>
      <HaloYukAbsenDuluAgar>
        {`Halo! yuk absen dulu, agar kehadiran kamu tercatat.`}
      </HaloYukAbsenDuluAgar>
      <HaloSelamatDatang>{`Halo, Selamat Datang!`}</HaloSelamatDatang>
      <Home>{`Home`}</Home>
      <Absen>{`Absen`}</Absen>
      <Instansi>{`Instansi`}</Instansi>
      <Rectangle2></Rectangle2>
      <Rectangle3></Rectangle3>
      <Rectangle4></Rectangle4>
      <Rectangle5></Rectangle5>
      <Rectangle7></Rectangle7>
      <Rectangle6></Rectangle6>
      <SilahkanIsiDataDiriK>
        {`Silahkan Isi Data Diri Kamu! 
Jangan Sampai Salah ya.`}
      </SilahkanIsiDataDiriK>
      <Nama>{`Nama`}</Nama>
      <Nip>{`NIP`}</Nip>
      <Bidang>{`Bidang`}</Bidang>
      <Jabatan>{`Jabatan`}</Jabatan>
      <Tanggal>{`Tanggal`}</Tanggal>
      <Absen1>{`Absen`}</Absen1>
      <SayaTelahMemasukkanD>
        {`Saya telah memasukkan data diri saya sesuai dengan kenyataan.`}
      </SayaTelahMemasukkanD>
      <DinasKomunikasiInfor>
        {`Dinas Komunikasi Informatika dan Statistik Kota Denpasar`}
      </DinasKomunikasiInfor>
      <Q0361431229>
        {`0361 - 431229
`}
      </Q0361431229>
      <KominfoDenpasarkotaG>
        {`kominfo@denpasarkota.go.id
`}
      </KominfoDenpasarkotaG>
      <KominfostatistikDenp>
        {`kominfostatistik.denpasarkota.go.id`}
      </KominfostatistikDenp>
      <FollowUs>{`Follow Us :`}</FollowUs>
      <JlMajapahitNo1DauhPu>
        {`Jl. Majapahit No 1, Dauh Puri Kaja, Kec. Denpasar Utara, Denpasar, Bali, 80231`}
      </JlMajapahitNo1DauhPu>
      <Facebook src={FacebookImage} loading="lazy" alt={'Facebook'} />
      <Instagram src={InstagramImage} loading="lazy" alt={'Instagram'} />
      <Twitter src={TwitterImage} loading="lazy" alt={'Twitter'} />
      <Youtube src={YoutubeImage} loading="lazy" alt={'Youtube'} />
      <S24822401></S24822401>
      <PngtreeSilhouetteOfR
        src={PngtreeSilhouetteOfRImage}
        loading="lazy"
        alt={'—Pngtree—silhouette of religious ceremony in_9011399 1'}
      />
    </Desktop51>
  );
}

export default Desktop5;
